defaults:
  - cluster/local
  - algorithm/dqn
  - environment/cartpole

hydra:
  run:
    dir: results/${algorithm}_${environment.name}/${autorl.seed}
  sweep:
    dir: results/${algorithm}_${environment.name}/${autorl.seed}
  job:
    chdir: true

load_checkpoint: ""

autorl:
  seed: 42
  env_framework: ${environment.framework}
  env_name: ${environment.name}
  n_envs: ${n_envs}
  algorithm: ${algorithm}
  cnn_policy: ${environment.cnn_policy}
  checkpoint: []
  checkpoint_name: "default_checkpoint"
  checkpoint_dir: "/tmp"
  objectives: ["reward_mean"]
  optimize_objectives: "upper"
  state_features: []
  n_steps: 10
  n_total_timesteps: ${environment.n_total_timesteps}
  n_eval_steps: 100
  n_eval_episodes: 10
