defaults:
  - _self_
  - /cluster: local
  - /algorithm: dqn
  - /environment: cc_cartpole
  - /search_space: dqn
  - override hydra/sweeper: HyperSMAC

hydra:
  sweeper:
    n_trials: 1000
    budget_variable: autorl.n_total_timesteps
    search_space: ${search_space}
    sweeper_kwargs:
      optimizer_kwargs:
        smac_facade:
          _target_: smac.facade.multi_fidelity_facade.MultiFidelityFacade
          _partial_: true
        intensifier:
          _target_: smac.facade.multi_fidelity_facade.MultiFidelityFacade.get_intensifier
          _partial_: true
          eta: 2
          n_seeds: 1
        scenario:
          n_trials: 1000
          seed: ${smac_seed}
          min_budget: 1000
          max_budget: ${environment.n_total_timesteps}
          deterministic: false
          n_workers: 1
      seeds: [0,1,2,3,4,5,6,7,8,9]
  run:
    dir: results/smac/${smac_seed}/${algorithm}_${autorl.env_name}/${autorl.seed}
  sweep:
    dir: results/smac/${smac_seed}/${algorithm}_${autorl.env_name}/${autorl.seed}
  job:
    chdir: true

load_checkpoint: ""
smac_seed: 0
jax_enable_x64: false
seed: 42

autorl:
  seed: ${seed}
  env_framework: ${environment.framework}
  env_name: ${environment.name}
  env_kwargs: ${environment.kwargs}
  n_envs: ${environment.n_envs}
  algorithm: ${algorithm}
  cnn_policy: ${environment.cnn_policy}
  n_total_timesteps: ${environment.n_total_timesteps}
  checkpoint: []
  checkpoint_name: "default_checkpoint"
  checkpoint_dir: "/scratch/hpc-prf-intexml/jbecktepe/arlbench_checkpoints/smac/"
  objectives: ["reward_mean"]
  optimize_objectives: "lower"
  state_features: []
  n_steps: 10
  n_eval_steps: 100
  n_eval_episodes: 10
