# @package _global_
algorithm: ppo
hp_config:
  clip_eps: '0.2'
  ent_coef: '0.01'
  gae_lambda: '0.95'
  gamma: '0.99'
  lr: '0.00025'
  max_grad_norm: '0.5'
  minibatch_size: '64'
  n_steps: '1024'
  update_epochs: '10'
  vf_coef: '0.5'
