# @package _global_
algorithm: sac
hp_config:
  alpha: '1.0'
  alpha_auto: 'True'
  buffer_alpha: '0.9'
  buffer_batch_size: '256'
  buffer_beta: '0.9'
  buffer_epsilon: 1e-05
  buffer_prio_sampling: 'False'
  buffer_size: '1000000'
  gamma: '0.99'
  gradient steps: '1'
  learning_starts: '100'
  lr: '0.0003'
  target_network_update_freq: '1'
  tau: '0.005'
  train_frequency: '1'
  use_target_network: 'True'
