# @package _global_
algorithm: "dqn"
cnn_policy: False

hp_config:
  lr: 0.01
  buffer_size: 1000000
  buffer_batch_size: 64
  buffer_prio_sampling: False
  buffer_alpha: 0.9
  buffer_beta: 0.9
  buffer_epsilon: 0.00001
  gamma: 0.99
  epsilon: 0.1
  tau: 0.1
  use_target_network: True
  train_frequency: 4
  gradient_steps: 1
  target_network_update_freq: 10
  learning_starts: 1000