seed: 0
hyperparameters:
  hp_config.buffer_alpha:
    type: uniform_float
    upper: 1.0
    lower: 0.01
    default: 0.9
    log: false
  hp_config.buffer_batch_size:
    type: categorical
    choices:
    - true
    - true
    - true
    - true
    default: true
  hp_config.buffer_beta:
    type: uniform_float
    upper: 1.0
    lower: 0.01
    default: 0.9
    log: false
  hp_config.buffer_epsilon:
    type: uniform_float
    upper: 0.01
    lower: 0.001
    default: 0.001
    log: false
  hp_config.buffer_prio_sampling:
    type: categorical
    choices:
    - true
    - false
    default: false
  hp_config.buffer_size:
    type: uniform_int
    upper: 10000000
    lower: 1024
    default: 1000000
    log: false
  hp_config.epsilon:
    type: uniform_float
    upper: 0.5
    lower: 0.005
    default: 0.1
    log: false
  hp_config.gamma:
    type: uniform_float
    upper: 1.0
    lower: 0.8
    default: 0.99
    log: false
  hp_config.gradient_steps:
    type: uniform_int
    upper: 10
    lower: 1
    default: 1
    log: false
  hp_config.learning_rate:
    type: uniform_float
    upper: 0.1
    lower: 1.0e-06
    default: 0.0003
    log: true
  hp_config.learning_starts:
    type: uniform_int
    upper: 1024
    lower: 0
    default: 128
    log: false
  hp_config.normalize_observations:
    type: categorical
    choices:
    - true
    - false
    default: false
  hp_config.train_freq:
    type: uniform_int
    upper: 128
    lower: 1
    default: 4
    log: false
  hp_config.use_target_network:
    type: categorical
    choices:
    - true
    - false
    default: true
  hp_config.target_update_interval:
    type: uniform_int
    upper: 1000
    lower: 1
    default: 1000
    log: false
  hp_config.tau:
    type: uniform_float
    upper: 1.0
    lower: 0.01
    default: 1.0
    log: false
conditions:
- child: target_update_interval
  parent: use_target_network
  value: true
  type: EQ
- child: tau
  parent: use_target_network
  value: true
  type: EQ
