seed: 0
hyperparameters:
  hp_config.buffer_prio_sampling:
    type: categorical
    choices: [True, False]
  hp_config.buffer_alpha:
    type: uniform_float
    upper: 1.0
    lower: 0.01
    log: false
  hp_config.buffer_beta:
    type: uniform_float
    upper: 1.0
    lower: 0.01
    log: false
  hp_config.buffer_epsilon:
    type: uniform_float
    upper: 1.0e-3
    lower: 1.0e-7
    log: true
  hp_config.buffer_batch_size:
    type: categorical
    choices: [16, 32, 64]
  hp_config.buffer_size:
    type: uniform_int
    upper: 100000
    lower: 1024
    log: false
  hp_config.learning_rate:
    type: uniform_float
    upper: 0.1
    lower: 1.0e-06
    log: true
  hp_config.learning_starts:
    type: uniform_int
    upper: 16384
    lower: 0
    default: 128
    log: false
  hp_config.use_target_network:
    type: categorical
    choices: [True, False]
  hp_config.target_update_interval:
    type: uniform_int
    upper: 2000
    lower: 1
    log: false
conditions:
  - child: hp_config.target_update_interval
    parent: hp_config.use_target_network
    value: true
    type: EQ
