seed: 0
hyperparameters:
  hp_config.clip_eps:
    type: uniform_float
    upper: 0.5
    lower: 0.0
    default: 0.2
    log: false
  hp_config.ent_coef:
    type: uniform_float
    upper: 0.5
    lower: 0.0
    default: 0.0
    log: false
  hp_config.gae_lambda:
    type: uniform_float
    upper: 0.9999
    lower: 0.8
    default: 0.95
    log: false
  hp_config.learning_rate:
    type: uniform_float
    upper: 0.1
    lower: 1.0e-06
    default: 0.0003
    log: true
  hp_config.max_grad_norm:
    type: uniform_float
    upper: 1.0
    lower: 0.0
    default: 0.5
    log: false
  hp_config.minibatch_size:
    type: categorical
    choices:
    - 16
    - 32
    - 64
    - 128
    default: 64
  hp_config.n_steps:
    type: categorical
    choices:
    - 32
    - 64
    - 128
    - 256
    - 512
    default: 128
  hp_config.normalize_advantage:
    type: categorical
    choices:
    - true
    - false
    default: true
  hp_config.update_epochs:
    type: uniform_int
    upper: 20
    lower: 5
    default: 10
    log: false
  hp_config.vf_clip_eps:
    type: uniform_float
    upper: 0.5
    lower: 0.0
    default: 0.2
    log: false
  hp_config.vf_coef:
    type: uniform_float
    upper: 1.0
    lower: 0.0
    default: 0.5
    log: false
conditions: []
