# @package _global_
defaults:
  - override /hydra/launcher: submitit_slurm

hydra:
  launcher:
    partition: dgx2
    gres: "gpu:1"
    timeout_min: 2880
    cpus_per_task: 2
    mem_per_cpu: 8000M
    account: supp0003
    setup:
      - export JAX_PLATFORM_NAME=gpu
      - source /rwthfs/rz/cluster/home/oh751555/i14/arlbench/.venv/bin/activate
