# @package _global_
defaults:
  - override /hydra/launcher: submitit_slurm

hydra:
  launcher:
    partition: ai,tnt
    gres: "gpu:1"
    timeout_min: 2880 # 2 days
    cpus_per_task: 16
    mem_gb: 16
    setup:
      - export JAX_PLATFORM_NAME=gpu
