# @package _global_
defaults:
  - override hydra/launcher: submitit_slurm

hydra:
  launcher:
    partition: ai
    cpus_per_task: 32
    gres: null
    timeout_min: 10080  # 7 days
    mem_gb: 64
    setup:
      - export JAX_PLATFORM_NAME=cpu
