# @package _global_
defaults:
  - override /hydra/launcher: submitit_slurm

hydra:
  launcher:
    partition: largemem
    cpus_per_task: 64
    mem_gb: 800
    gres: null
    timeout_min: 2880
    setup:
      - export JAX_PLATFORM_NAME=cpu