# @package _global_
defaults:
  - override /hydra/launcher: submitit_slurm

hydra:
  launcher:
    partition: gpu
    gpus_per_task: 1
    gres: "gpu:a100:1"
    timeout_min: 2880
    setup:
      - export JAX_PLATFORM_NAME=gpu
