# @package _global_
defaults:
  - override /hydra/launcher: submitit_slurm

hydra:
  launcher:
    partition: normal
    cpus_per_task: 8
    mem_per_cpu: 2GB
    gres: null
    timeout_min: 2880
    setup:
      - export JAX_PLATFORM_NAME=cpu
