seed: 0
hyperparameters:
  buffer_batch_size:
    name: buffer_batch_size
    type: categorical
    choices:
      - 4
      - 8
      - 16
      - 32
      - 64
      - 128
      - 256
    default: 32
  learning_rate:
    name: learning_rate
    type: uniform_float
    upper: 0.1
    lower: 1.0e-06
    default: 0.0003
    log: true
  # use_target_network:
  #   name: use_target_network
  #   type: categorical
  #   choices:
  #     - true
  #     - false
  #   default: true
  # tau:
  #   name: tau
  #   type: uniform_float
  #   upper: 1.0
  #   lower: 0.001
  #   default: 0.01
  #   log: false
  gamma:
    name: gamma
    type: uniform_float
    upper: 1.0
    lower: 0.5
    default: 0.99
    log: false
# conditions:
#   - child: tau
#     parent: use_target_network
#     value: true
#     type: EQ
