defaults:
  - _self_
  - /algorithm: redo_dqn
  - /environment: cc_cartpole
  - search_space: dqn

hydra:
  run:
    dir: results/reset_00001_dqn_${environment.name}/${autorl.seed}
  sweep:
    dir: results/reset_00001_dqn_${environment.name}/${autorl.seed}
  job:
    chdir: true

jax_enable_x64: false
load_checkpoint: ""

autorl:
  seed: 42
  env_framework: ${environment.framework}
  env_name: ${environment.name}
  env_kwargs: ${environment.kwargs}
  eval_env_kwargs: ${environment.eval_kwargs}
  n_envs: ${environment.n_envs}
  algorithm: ${algorithm}
  cnn_policy: ${environment.cnn_policy}
  nas_config: ${nas_config}
  n_total_timesteps: ${environment.n_total_timesteps}
  checkpoint: []
  checkpoint_name: "default_checkpoint"
  checkpoint_dir: "/tmp"
  state_features: []
  objectives: ["reward_mean"]
  optimize_objectives: "upper"
  n_steps: 1
  n_eval_steps: 100
  n_eval_episodes: 10
  weight_recycler_config: 
    weight_recycler: "primacy"
    reset_period: 10000
    reset_end_step: ${environment.n_total_timesteps}
  manual_epsilon: true
  epsilon: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]
  offline_update_fraction: 0.0001
  manual_offline_updates: false