defaults:
  - _self_
  - /algorithm: dqn
  - /environment: cc_cartpole
  - search_space: dqn_no_cond
  - override hydra/sweeper: HyperPBT

hydra:
  sweeper:
    budget: ${eval:'${environment.n_total_timesteps} * ${pbt_iterations}'}
    budget_variable: autorl.n_total_timesteps
    loading_variable: load
    saving_variable: save
    sweeper_kwargs:
      optimizer_kwargs:
        population_size: 8
        config_interval: 1e4
        seed: ${autorl.seed}
      checkpoint_tf: true
      load_tf: true
      checkpoint_path_typing: ""
      maximize: true
    search_space: ${search_space}
  run:
    dir: results/pbt_${environment.name}/${autorl.seed}
  sweep:
    dir: results/pbt_${environment.name}/${autorl.seed}
  job:
    chdir: true

jax_enable_x64: false
load_checkpoint: ""
pbt_iterations: 10
save: false
load: false

autorl:
  seed: 42
  env_framework: ${environment.framework}
  env_name: ${environment.name}
  env_kwargs: ${environment.kwargs}
  eval_env_kwargs: ${environment.eval_kwargs}
  n_envs: ${environment.n_envs}
  algorithm: ${algorithm}
  cnn_policy: ${environment.cnn_policy}
  nas_config: ${nas_config}
  n_total_timesteps: ${environment.n_total_timesteps}
  checkpoint: []
  checkpoint_name: "default_checkpoint"
  checkpoint_dir: "/tmp"
  state_features: []
  objectives: ["reward_mean"]
  optimize_objectives: "upper"
  n_steps: ${pbt_iterations}
  n_eval_steps: 100
  n_eval_episodes: 10
  
