defaults:
  - _self_
  - /algorithm: redo_dqn
  - /environment: cc_cartpole
  - /experiment: cc_cartpole_dqn
  - search_space: dqn_rbt
  - cluster: local

jax_enable_x64: false
load_checkpoint: ""
remove_checkpoints: true

replay_ratio: 0.1
use_default_for_rollouts: false
continuous_smac: true
optimize_replay_ratio: true

n_iterations: 10
eval_criterion: eval_return
n_eval_episodes: 128
hb_min_budget: ${eval:'${hb_max_budget} / 10'}
hb_max_budget: ${replay_ratio}
budget_per_iteration:  ${eval:'16 * ${hb_max_budget}'}
hb_eta: 2
n_configs_per_iteration: 16
n_hb_configs_per_iteration: 22
optimizer: smac

autorl:
  seed: 42
  env_framework: ${environment.framework}
  env_name: ${environment.name}
  env_kwargs: ${environment.kwargs}
  eval_env_kwargs: ${environment.eval_kwargs}
  n_envs: ${environment.n_envs}
  algorithm: ${algorithm}
  cnn_policy: ${environment.cnn_policy}
  nas_config: ${nas_config}
  n_total_timesteps: ${eval:'${environment.n_total_timesteps} // ${n_iterations}'}
  checkpoint: ["opt_state", "params"]
  checkpoint_name: "default_checkpoint"
  checkpoint_dir: "./checkpoints"
  state_features: []
  objectives: ["reward_mean"]
  optimize_objectives: "upper"
  n_steps: ${n_iterations}
  n_eval_steps: 10
  n_eval_episodes: 128
  weight_recycler_config: 
    weight_recycler: "primacy"
    reset_period: ${eval:'${environment.n_total_timesteps} // ${n_iterations}'}
    reset_end_step: ${environment.n_total_timesteps}
  manual_epsilon: true
  epsilon: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]
  replay_ratio: 0.0
  manual_offline_updates: true
  manual_recycling: true
  validation_size: 0
  visualize_buffer: false
  reset_layers: ["dense1", "out_layer"]
  
hydra:
  output_subdir: "."
  run:
    dir: results/${environment.name}/rbt-mediumreset-optbudget-cont_${optimizer}_${replay_ratio}_${eval_criterion}
  sweep:
    dir: results/${environment.name}/rbt-mediumreset-optbudget-cont_${optimizer}_${replay_ratio}_${eval_criterion}
    subdir: ${autorl.seed}
  job:
    chdir: true