# @package _global_
defaults:
  - override /environment: brax_ant    
  - override /algorithm: sac    

# https://huggingface.co/sb3/sac-Ant-v3
environment:
  n_envs: 1
  n_total_timesteps: 1000000

hp_config:
  normalize_observations: True
