# @package _global_
defaults:
  - /environment: cc_acrobot
  - /algorithm: dqn

# https://huggingface.co/sb3/dqn-Acrobot-v1
override /environment/n_envs: 1
override /environment/n_total_timesteps: 100000

override /hp_config/buffer_batch_size: 128
override /hp_config/buffer_size: 50000
# since we do not support epsilon schedules we stick to 0.1 here
override /hp_config/epsilon: 0.1
override /hp_config/gamma: 0.99
override /hp_config/gradient_steps: 4
override /hp_config/learning_rate: 0.00063
override /hp_config/target_update_interval: 250
override /hp_config/train_freq: 4
override /hp_config/learning_starts: 0

override /nas_config/hidden_size: 256
