# @package _global_
defaults:
  - /environment: cc_continuous_mountain_car
  - /algorithm: ppo

# https://huggingface.co/sb3/ppo-MountainCarContinuous-v0
override /environment/n_envs: 1
override /environment/n_total_timesteps: 20000

override /hp_config/minibatch_size: 256
# since we do not support clip_eps schedules we set clip_eps to a fixed value
override /hp_config/clip_eps: 0.1
override /hp_config/ent_coef: 0.00429
override /hp_config/gae_lambda: 0.9
override /hp_config/gamma: 0.9999
# since we do not support learning rate schedules we set learning_rate to a fixed value
override /hp_config/learning_rate: 7.77e-05
override /hp_config/update_epochs: 10
override /hp_config/n_steps: 8
override /hp_config/max_grad_norm: 5
override /hp_config/vf_coef: 0.19
