# @package _global_
defaults:
  - override /environment: cc_cartpole    
  - override /algorithm: dqn  

# https://huggingface.co/sb3/dqn-CartPole-v1
environment:
  n_envs: 1
  n_total_timesteps: 50000

hp_config:
  buffer_batch_size: 64
  buffer_size: 100000
  # since we do not support epsilon schedules we stick to 0.1 here
  epsilon: 0.1
  gamma: 0.99
  gradient_steps: 1
  learning_rate: 0.0023
  target_update_interval: 10
  train_freq: 2
  normalize_observations: False

nas_config:
  hidden_size: 256
