# @package _global_
defaults:
  - override /environment: cc_pendulum    
  - override /algorithm: ppo       

# https://huggingface.co/sb3/ppo-Pendulum-v1
environment:
  n_envs: 1
  n_total_timesteps: 20000

hp_config:
  minibatch_size: 256
  # since we do not support clip_eps schedules we set clip_eps to a fixed value
  clip_eps: 0.1
  ent_coef: 0.00429
  gae_lambda: 0.9
  gamma: 0.9999
  # since we do not support learning rate schedules we set learning_rate to a fixed value
  learning_rate: 7.77e-05
  update_epochs: 10
  n_steps: 8
  max_grad_norm: 5
  vf_coef: 0.19
  normalize_observations: False
