# @package _global_
defaults:
  - override /environment: mujoco_halfcheetah    
  - override /algorithm: sac    

# https://huggingface.co/sb3/sac-HalfCheetah-v3
environment:
  n_envs: 1
  n_total_timesteps: 1000000

hp_config:
  learning_starts: 10000
  normalize_observations: True

jax_enable_x64: True
