# @package _global_
defaults:
  - override /environment: procgen_bigfish_easy    
  - override /algorithm: ppo    

# https://arxiv.org/pdf/1912.01588
environment:
  n_envs: 1
  n_total_timesteps: 200e6

hp_config:
  gae_labmda: 0.95
  n_steps: 256
  minibatch_size: 32
  ent_coef: 0.01
  clip_eps: 0.2
  learning_rate: 5e-4
  normalize_observations: False