# @package _global_
defaults:
  - override /environment: procgen_bigfish_hard   
  - override /algorithm: dqn    

# https://arxiv.org/pdf/1912.01588
environment:
  n_envs: 1
  n_total_timesteps: 200e6

hp_config:
  normalize_observations: False

nas_config:
  activation: relu
  hidden_size: 256
